### ISSUE TITLE
Missing dependency 'packaging'

### ISSUE THREAD

**Issue by frisitano** [reef-defi/py-reef-interface#1]
There appears to be a missing dependency.  

When I try to import the ReefInterface class:

`>>> from reefinterface import ReefInterface`

I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py-reef-interface/lib/python3.8/site-packages/reefinterface/__init__.py", line 18, in <module>
    from .contracts import *
  File "/anaconda3/envs/py-reef-interface/lib/python3.8/site-packages/reefinterface/contracts.py", line 19, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

`setup.py`, `requirements.txt` and `Pipfile` should be updated to include this dependency.  Creating a new release upon the resolution should be considered as the latest release hosted on pypy suffers from this issue.

**Comment by frisitano** [comment]
Resolved by #2
